### ISSUE TITLE
Cannot allow to specify not to download `native-image` component

### ISSUE THREAD

**Issue by linghengqian** [graalvm/graalvm-jdk-downloader#5]
- I noticed that in https://github.com/graalvm/graalvm-jdk-downloader/actions/runs/4018232570/jobs/6903673688, the bash command actively downloaded `native-image` component without specifying `-c native-image` .
- I verified this behavior in Dockerfile, if we execute `bash <(curl -sL https://get.graalvm.org/jdk) -c espresso graalvm-ce-java17-22.3.1`, it will not only download `espresso` component, also downloads the `native-image` component.
- ![image](https://user-images.githubusercontent.com/20187731/216546696-f615007b-bce2-4b78-adf3-d0b3f9b4108e.png)
- This comes from my investigation of https://github.com/apache/shardingsphere/issues/21347. Since Truffle Espresso is used when packaging the GraalVM Native Image of Apache ShardingSphere Proxy, and https://github.com/oracle/graal/issues/4555 has not been closed, I must pass `bash <(curl -sL https:/ /get.graalvm.org/jdk) -c espresso graalvm-ce-java17-22.3.1` to explicitly download the Espresso files. It would be nice if the bash command had a way to prevent the download of the `native-image` component. This reduces the size of the final Docker Image because the GraalVM Native Image binary is compiled before starting to package the Docker Image.

**Comment by fniephaus** [comment]
Thanks for raising this issue, @linghengqian. As you found out, `native-image` is always installed by default and we do not have any plans to change this.

> This reduces the size of the final Docker Image because the GraalVM Native Image binary is compiled before starting to package the Docker Image.

I'm not sure I understand: If you build the application with Native Image and Espresso, you no longer need a full GraalVM installation when deploying the application. Are you sure you need a GraalVM installation in your Docker container?

**Comment by linghengqian** [comment]
- I have tested to run GraalVM Native Image within Truffle Espresso, and it does not require a full installation of GraalVM CE, but requires a common JVM and Truffle Espresso specific files, and Espresso files must be located in `$GRAALVM_HOME/languages/java`,  This is the weirdest bit that I think https://github.com/oracle/graal/issues/4555 brings up.  In my understanding, if I don't install GraalVM CE, downloading Espresso files is a matter of not knowing where to start.

- https://github.com/oracle/graal/issues/4555 behaves like this on GraalVM CE 22.3.1, am I understanding something wrong?

**Comment by fniephaus** [comment]
Right, I believe fixing https://github.com/oracle/graal/issues/4555 is the right thing to do here. Until then, your containers may be a bit bigger. As a workaround, you could `gu remove native-image` again, right after using the GraalVM JDK downloader scripts.

I hope you don't mind if I'm closing this for now.

**Comment by linghengqian** [comment]
- Thanks, I will use `gu remove` command in Dockerfile.
