### ISSUE TITLE
[FEATURE REQUEST] Get the latest/default version to be downloaded, e.g., graalvm-ce-java17-22.3.1 as plain text

### ISSUE THREAD

**Issue by audacioustux** [graalvm/graalvm-jdk-downloader#6]
it would be nice if i could `curl bash <(curl -sL https://get.graalvm.org/release/latest)`, and get the default release to be installed as plain text, like `graalvm-ce-java17-22.3.1` or `graalvm-ee-java17-22.3.1` (based on availability of $GRAAL_EE_DOWNLOAD_TOKEN)

without this, it's a bit inconvenience to get what version is actually installed (maybe parsing `ls` output), when the intent is to install the latest version

**Comment by fniephaus** [comment]
Apologies for not looking into this sooner. Were you able to work around the problem? The new release just made it into SDKMAN (both CE and Oracle GraalVM) and it may be easier to use that in the future. What do you think?

**Comment by audacioustux** [comment]
np... and yah, found out the Oracle GraalVM yesterday. I couldn't find the new release in sdkman yesterday, so, with the new script friendly URLs - written (copied from official Dockerfile) a script instead https://raw.githubusercontent.com/audacioustux/CompaaS/a2fefa0c3686d452bf1b8a05080571553632ea8f/.devcontainer/features/graalvm/install.sh
may switch to sdkman later

**Comment by fniephaus** [comment]
Great! Yes, the new script friendly URLs are designed for exactly this. :)
